
package org.silentsoft.actlist.version;

/* Automatically generated by ant. */
public class BuildVersion {
	public static final String VERSION = "2.1.0";
	public static final String BUILD_TIME = "20200810-011456";
}
		