
package org.silentsoft.actlist.version;

/* Automatically generated by ant. */
public class BuildVersion {
	public static final String VERSION = "1.7.0";
	public static final String BUILD_TIME = "20200202-215930";
}
		