
package org.silentsoft.actlist.version;

/* Automatically generated by ant. */
public class BuildVersion {
	public static final String VERSION = "2.0.1-SNAPSHOT";
	public static final String BUILD_TIME = "20200414-011013";
}
		